#coding=utf-8

# Chinese regin name
TAOYUAN =   '桃園'
YILAN =     '宜蘭'
TAICHUNG =  '台中'
KAOHSIUNG = '高雄'
TAITUNG =   '台東'

# Chinese prodoct name
BASIL =         '九層塔'
GARLIC =        '大蒜'
BOK_CHOY =      '小白菜'
CORN =          '玉米'
SWEET_POTATO =  '地瓜'
BAMBOO_SHOOT =  '竹筍'
WATERMELON =    '西瓜'
MANGO =         '芒果'
BROCCOLI =      '花椰菜'
SPOON_CABBAGE = '青江菜'
SHALLOT =       '青蔥'
PUMPKIN =       '南瓜'
ONION =         '洋蔥'
BANANA =        '香蕉'
STRAWBERRY =    '草莓'
POTATO =        '馬鈴薯'
CABBAGE =       '高麗菜'
SWEET_PEPPER =  '甜椒'
PONKAN =        '椪柑'
TOMATO =        '番茄'
SPINACH =       '菠菜'
GRAPE =         '葡萄'
CHILI =         '辣椒'
PINEAPPLE =     '鳳梨'
APPLE =         '蘋果'
RADISH =        '蘿蔔'
