
key_date = 'date'
key_region = 'region'
key_temperature = 'temperature'
key_rainfall = 'rainfall'
key_humidity = 'humidity'

key_product = 'product'
key_price = 'price'
key_turnover ='turnover'
key_trading_data = 'trading_data'
key_taoyuan = 'TY'
key_yilan = 'YL'
key_taichung = 'TC'
key_kaohsiung = 'KS'
key_taitung = 'TT'